.PHONY: build clean

FC:=gfortran-4.6
LLC:=llvm-as
WLD:=wasm-ld
FCFLAGS:=-S -flto -m32 -fplugin=/app/dragonegg-3.3.src/dragonegg.so
LLCFLAGS:=-march=wasm32 -filetype=obj
WLDFLAGS:=--no-entry --export-all

BLDPATH:=bin
SRCPATH:=src
STAPATH:=static

NAME:=testlib
BIN:=$(BLDPATH)/$(NAME).wasm
SRCS:=$(wildcard $(SRCPATH)/*.f90)
LLS:=$(SRCS:$(SRCPATH)/%.f90=$(BLDPATH)/%.ll)
OBJS:=$(SRCS:$(SRCPATH)/%.f90=$(BLDPATH)/%.o)


build: clean $(BIN)
	cp -f $(STAPATH)/* $(BLDPATH)/

$(LLS): $(BLDPATH)/%.ll: $(SRCPATH)/%.f90
	mkdir -p $(BLDPATH)
	$(info Compiling to intermediate: $<)
	$(FC) $(FCFLAGS) $< -o $@

$(OBJS): $(BLDPATH)/%.o: $(BLDPATH)/%.ll
	mkdir -p $(BLDPATH)
	$(info Assembling to object: $<)
	$(LLC) $(LLCFLAGS) $< -o $@

$(BIN): $(OBJS)
	mkdir -p $(BLDPATH)
	$(info Linking)
	$(WLD) $(WLDFLAGS) -o $(BIN) $(OBJS)
	

clean:
	rm -f $(LLS) $(OBJS) $(BIN)